### ISSUE TITLE
Publish to npm for easier usage

### ISSUE THREAD

**Issue by NEO97online** [sporadic-labs/tile-extruder#1]
Can we get this published to npm so we can install it globally? Would be much easier than having to always run from the cloned folder.

If you want me to take care of this, I can set it up to run as an executable and help publish to npm for global install. Just assign this issue back to me if you'd like me to do it.

**Comment by mikewesthad** [comment]
@hermbit, that would be wonderful! Thanks

**Comment by mikewesthad** [comment]
Thanks for suggestion. I had a few minutes this evening, so I got it set up on npm.

I think the next step in usability is probably to create a web app version so that no one has to install anything.
