### ISSUE TITLE
Wrong tile output size 

### ISSUE THREAD

**Issue by m3talstorm** [sporadic-labs/tile-extruder#13]
- Take the image label `First image` from here: https://imgur.com/a/gv24oyc
- Run `tile-extruder --tileWidth 32 --tileHeight 32 --margin 1 --spacing 2 --input path/to/first_image.png --output path/to/second_image.png`
- This outputs the image generated labelled `Second image`
- Notice that the tile size of the output image is `34x34`! (Loaded in Photoshop, with a 32x32 region shown - image labelled `third image`)

**Comment by mikewesthad** [comment]
@m3talstorm, howdy, I'm not sure I understand what you are saying. Tile extruder purposefully increases the size of the tiles by extruding them - see the explanation image:

<img src="https://github.com/sporadic-labs/tile-extruder/blob/master/doc-source/images/explanation.png?raw=true">

The tool is working as intended. When you load the extruded tileset into your game engine of choice, you still treat it as having the same tile size (the extruded bits become margin+spacing). See the [using extruded tileset](https://github.com/sporadic-labs/tile-extruder#using-the-extruded-tileset) section of the readme.

As far as I can tell from your files, your tile size is either 34 or 68. Your tileset image also doesn't appear to have any margin or spacing, so you don't want to use those parameters.
