### ISSUE TITLE
Make outputPath optional

### ISSUE THREAD

**Issue by Naxos84** [sporadic-labs/tile-extruder#15]
Would it be possible to make the outputPath optional?

If no outputPath is provided then we could just append an "_extruded" to the filename of the inputPath.

I even would try to come up with a PR. But I want to check wether that is ok for you.

**Comment by mikewesthad** [comment]
Would happily accept a PR! That sounds like a reasonable default to me, for folks who want to cut down on typing. Original image path + "_extruded" + original file extension would be good. Feel free to ping this thread if you give it a go and have any questions.

**Comment by Naxos84** [comment]
Alright.

I started implementing it.
Have a working example (tested it with the example files)

Questions that I have:

How much should the test's be extended to check this behaviour. Cause the default value behaviour comes from `tile-extruder`
I don't get how the doc is generated. I added something to JsDoc that is not present in generated file.
Besides that the `cp` command (for `npm run postdoc`) does not work on Windows machines ;)

**Comment by mikewesthad** [comment]
Cool! 

Don't worry about adding any tests. `test.js` is a custom snapshot style test for running the CLI, and I think this sort of thing would be better checked with something more like a unit test (which is not currently set up in this repository).

Ahh, I'm on Windows, but I use Git Bash and WSL as my terminal. I just pushed a fix to make the postdoc script cross platform compatible. If you are able to test the docs locally, great. If not, don't worry - I'll check them out in the PR.

**Comment by mikewesthad** [comment]
All set - updated the readme with the new docs, added a credit in the contributions & changelog sections and published to npm. Thanks!
