### ISSUE TITLE
Width not divisible by tile size

### ISSUE THREAD

**Issue by Antix-Development** [sporadic-labs/tile-extruder#20]
If your tileset dimensions are not evenly divisible by your tile size then this application does not output the desired result.

I have a tileset image that is 1024x2048 in size but my tiles are 24x24 in size. 

Running this application on my tileset results in incorrectly sized output.

It would be nice if this application could accommodate such a corner case.

**Comment by mikewesthad** [comment]
Hiya @Antix-Development - could you explain a bit more about why your tileset image isn't a multiple of your tile size? 

The idea of extruding tiles requires a bit more configuration when an image isn't a multiple of the tile size. If it isn't a multiple, then the tool needs to know where the bounding box for where the tile parts of your image are located (e.g. if there's stuff at the top left of the image, the extrusions algorithm can't start at 0,0) and how to treat the non tile areas of the image (e.g. if the tileset is embedded in an atlas image where the other stuff shouldn't be extruded).

**Comment by Antix-Development** [comment]
I really just wanted to have my textures power of 2 sized really.

I've resized my texture size and it all works now.

You might as well close this issue if it's a big hassle to implement :)

**Comment by mikewesthad** [comment]
Ah, I see - I'll have to think on it this week

**Comment by mikewesthad** [comment]
Doing some cleanup and re-evaluating this issue. I think this would complicate the CLI, but I'm planning on building a simple web app GUI and will consider it for that.
