### ISSUE TITLE
Does this works with POT tile sizes only?

### ISSUE THREAD

**Issue by jackfreak** [sporadic-labs/tile-extruder#3]
Hi, my game has tiles of 50x50px, it's not pixel art so I don't need POT sizes. 
The tileset texture is 2048x2048.  

When I execute this command:
tile-extruder --tileWidth 50 --tileHeight 50 --input ./levels/common/tiles/Tileset_g50.png --output ./levels/common/tiles/Tileset_g50_extruded.png

I get this error:
"Non-integer number of rows or cols found. The image doesn't match the specified parameters. Double check your margin, spacing, tileWidth and tileHeight."

**Comment by mikewesthad** [comment]
Hi @jackfreak - POT is not a requirement, but it does require that your texture's overall width/height match your tile size, margin and spacing. So without margin/spacing, it would expect 2050 x 2050. Does your tileset have margin and/or spacing? You need to pass those in with the command, e.g. `--margin 2 --spacing 1`

**Comment by jackfreak** [comment]
Thank you for your answer!

**Comment by mikewesthad** [comment]
No problem
