### ISSUE TITLE
Not work in CANVAS type

### ISSUE THREAD

**Issue by ReydVires** [sporadic-labs/tile-extruder#4]
like the title.
on Phaser version **Phaser v3.16.2**
browser **Firefox 66.0.2 (64-bit)**
It's work correctly on WebGL, but not for CANVAS

**Comment by mikewesthad** [comment]
Interesting, thanks for the report. I'm seeing this in FF and Edge in CANVAS when running the `phaser-test` in the repo. Both are fine in WEBGL, and Chrome works in both CANVAS and WEBGL.

![image](https://user-images.githubusercontent.com/1131802/55686445-d6453580-5926-11e9-922a-275696f23763.png)
> Left is unextruded and right is extruded

This could be a bug in the Phaser renderer, an issue inherent to canvas, or a bug in the demo code. Will have to look into this further.

**Comment by mikewesthad** [comment]
@ReydVires, here's my understanding. I believe this is a fundamental issue with canvas rendering. There's nothing to fix with the tile-extruder CLI, so I'm going to close this issue.

With canvas mode, Phaser draws each tile via `ctx.drawImage`. If you are drawing tiles at floating point positions / float point scales with canvas in FF/Edge, the anti-aliasing filter that gets applied to each tile causes the background to bleed through the tiles. 

This happens with the raw canvas API:
![image](https://user-images.githubusercontent.com/1131802/55689995-6dbf7e00-5951-11e9-8630-7a59c82e4bf8.png)

See [codesandbox](https://codesandbox.io/s/zn5vxpj1yl) for demo and a possible fix. If you draw your tiles to an offscreen buffer and then draw that to the screen, it eliminates the FF/Edge issue in my simple test. That approach might work in Phaser's renderer. My recommendation would be to bring this up in the Phaser slack/discord or via an issue over there. Feel free to reference this issue or codesandbox. If you do, please do keep me posted of what comes of it.
