### ISSUE TITLE
Thank you !

### ISSUE THREAD

**Issue by lc-thomas** [sporadic-labs/tile-extruder#5]
Hello!
I'm just dropping by to say hello and thank you !

Your article on phaser / tiled for a top-down RPG helped me a lot to get started with phaser.
And now using your tile extruder my tiles aren't bleeding anymore :)

So big thanks from France! Have a beautiful day.

![Screenshot from 2019-07-07 05-34-21](https://user-images.githubusercontent.com/1223217/60763639-e6c99100-a078-11e9-891c-ae12645b84b0.png)

**Comment by mikewesthad** [comment]
👍 glad you found them helpful!
