### ISSUE TITLE
Extruding a tileset introduces grey shadows to tiles

### ISSUE THREAD

**Issue by FranciscoCaetano88** [sporadic-labs/tile-extruder#8]
Original: 
![image](https://user-images.githubusercontent.com/28624860/70641703-ef308400-1c35-11ea-91e1-a960d460b40d.png)

Extruded:
![image](https://user-images.githubusercontent.com/28624860/70641731-fa83af80-1c35-11ea-94ae-a8e6a44fb86e.png)

It's mostly noticeable in the water tiles. I've had this same tileset extruded before in an older version and it was good.. Please help!

**Comment by mikewesthad** [comment]
Hi @FranciscoCaetano88 - looks like your transparent pixels are being blended against a black color. Can you try again using the color option: "-c 0xFFFFFF00"?

**Comment by mikewesthad** [comment]
Ahh, I see now. It looks like the latest version of Jimp started using alpha blending by default when "blitting" from one image to another. I'll need to investigate this further tomorrow to figure out the best way to fix the library. Thanks for the bug report.

In the meantime, you should be able to use tile-extruder@2.0.1 for now. That version uses the old version of Jimp.

**Comment by mikewesthad** [comment]
Should be fixed in the latest release now (v2.0.3). Thanks!
